Create database php_db;

use php_db;

CREATE TABLE `member` (
    `MEMBER_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'key' ,
    `NAME` VARCHAR(10) NULL DEFAULT NULL COMMENT '이름' CHECK (NAME <> ''),
    `AGE` tinyint NULL DEFAULT NULL COMMENT '나이' CHECK (AGE <>''),
    `SEX` VARCHAR(4) NULL DEFAULT NULL COMMENT '성별' CHECK(SEX<>''),
    `ADDR` VARCHAR(50) NULL DEFAULT NULL COMMENT '주소' CHECK(ADDR<>''),
    `PHONE` VARCHAR(20) NULL DEFAULT NULL COMMENT '전화번호' CHECK(PHONE<>''),
    PRIMARY KEY (`MEMBER_ID`),
    INDEX `IDX_NAME` (`NAME`)
);
